### ISSUE TITLE
Update docker image with some key packages

### ISSUE THREAD

**Issue by shakeelmohamed** [loganknecht/Stanford_CS1_Compilers#2]
I had to manually install `ssh` (for git), `vim`, and `make`. We should have at least those pre-installed

**Comment by loganknecht** [comment]
@shakeelmohamed I've created the dockerfile, but I'm having some issues getting it to mount the repository correctly to the path I want.

Can you help me finish this so I can start working on the first assignment?

**Comment by shakeelmohamed** [comment]
@loganknecht yeah let's knock it out today

**Comment by loganknecht** [comment]
@shakeelmohamed 
Managed to fix the issues with the docker file. It turns out volumes can't be mounted in docker files for synchronous usage. That can only be done at run time with the -v flag.

http://stackoverflow.com/questions/26050899/how-to-mount-host-volumes-into-docker-containers-in-dockerfile-during-build

Also there's a big difference between the RUN/CMD/ENTRYPOINT commands that I don't really understand, something to do with the image layers being built in between with containers for the RUN command? and CMD only is called if you run the image without any parameters? Again, not really sure.

Either way this is fixed.
